headers = []
redirects = []

[functions]

[functions.emails]
included_files = ["./emails/**"]

[functions."*"]

[[plugins]]
origin = "ui"
package = "@netlify/plugin-emails"
pinned_version = "1"

[plugins.inputs]

[build]
publish = "/home/neo/netlify-dev-hub/backend"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]